Feature/cldn 1576
CybercentreCanada/datahub pull request #18
Opened 2023-06-13 18:07 UTC by cccs-Dustin

This PR incorporates the changes requested in the CLDN-1576 ticket ([link](https://cccs.atlassian.net/browse/CLDN-1576))

**Major Changes Include:**
- Added a new `partition_spec` value to the properties tab of Iceberg tables in DataHub
- Updated the integration tests to use a new custom test table (and updated the golden files)
- Fixed a versioning issue with the `typing_extensions` package

2023-06-13 18:25 UTC, cccs-tom approved these changes

2023-06-14 11:37 UTC, cccs-eric approved these changes

2023-06-14 14:41 UTC, cccs-eric requested changes

2023-06-14 14:41 UTC, cccs-eric commented on metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_profiler.py
> +        except Exception as e:
I'd add a simple comment explaining why we catch exceptions here and not everywhere.  Something that summarizes what we have discussed in chat.  Otherwise devs will wonder why we log warnings here and not everywhere.

2023-06-14 14:50 UTC, cccs-Dustin commented on metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg_profiler.py
> +        except Exception as e:
Does this explain it? If so, I will add it in a new commit.

`# Catch any errors that arise from attempting to read the Iceberg table's manifests`

2023-06-14 17:27 UTC, cccs-RyanK approved these changes

2023-06-14 18:46 UTC, cccs-eric approved these changes

2023-06-14 18:48 UTC, merged