Feature/stateful iceberg source
CybercentreCanada/datahub pull request #5
Opened 2022-10-31 12:37 UTC by cccs-Dustin

This PR incorporates the changes outlined in the CLDN-1776 ticket ([link](https://cccs.atlassian.net/browse/CLDN-1776)):

**Major code changes include:**
- Updated the `iceberg` source to make it stateful
- Updated the corresponding `iceberg` source documentation to show this change
- Modified existing `iceberg` source integration tests (& golden files), as well as made a new integration test

2022-11-01 16:27 UTC, cccs-tom commented on metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
> +        self.platform: str = "iceberg"
For a second, I thought this might be a relic of @cccs-eric's JAva dev days, but apparently, it is also a convention in Python to name constants in `MACRO_SNAKE_CASE`. Was there a reason you changed this? Is it no longer constant?

2022-11-01 16:27 UTC, cccs-tom commented on metadata-ingestion/src/datahub/ingestion/source/state/iceberg_state.py
> +        if type == "table":
This `"table"` value should be extracted into a constant

2022-11-01 17:14 UTC, cccs-Dustin commented on metadata-ingestion/src/datahub/ingestion/source/state/iceberg_state.py
> +        if type == "table":
I only wrote it in this fashion to follow along with what the Kafka `state` file does:

https://github.com/CybercentreCanada/datahub/blob/e29fafa2cc20f1105c4815d853432c31b59a20bb/metadata-ingestion/src/datahub/ingestion/source/state/kafka_state.py#L47-L50

However, if you would still like me to extract the value into a constant I can do that.

2022-11-01 17:23 UTC, cccs-tom commented on metadata-ingestion/src/datahub/ingestion/source/state/iceberg_state.py
> +        if type == "table":
Reading up on this, it seems that constants are rarely used in Python - and especially not in a case like this where all uses are in the same file. Also, constants are purely a convention in Python. There is no `const` keyword or anything else actually preventing someone from assigning a different value to a constant. It's just a variable that uses a different naming convention to indicate it shouldn't be assigned... So let's leave it - no need to change this!

2022-11-01 18:56 UTC, cccs-Dustin commented on metadata-ingestion/src/datahub/ingestion/source/iceberg/iceberg.py
> +        self.platform: str = "iceberg"
After testing with `self.PLATFORM`, it still results in an error during ingestion. Based on the dbt and Kafka sources, I believe it should be `self.platform`:

https://github.com/datahub-project/datahub/blob/873b100a47a492610eb7386ac12e39487bee7ef2/metadata-ingestion/src/datahub/ingestion/source/kafka.py#L199

https://github.com/datahub-project/datahub/blob/873b100a47a492610eb7386ac12e39487bee7ef2/metadata-ingestion/src/datahub/ingestion/source/dbt.py#L995

2022-11-01 19:09 UTC, cccs-tom commented
I'm approving this. But just for simplicity, especially since we plan to cherry-pick this feature to upstream, it would be a good idea to rebase all of these commits into one, imo.

2022-11-02 12:44 UTC, cccs-eric requested changes

2022-11-02 12:44 UTC, cccs-eric commented on metadata-ingestion/tests/integration/iceberg/test_iceberg.py
> +        deleted_mces_path = "{}/{}".format(tmp_path, "iceberg_deleted_mces.json")
```suggestion
        deleted_mces_path = f"{tmp_path}/{iceberg_deleted_mces.json}"
```

2022-11-02 12:46 UTC, cccs-eric commented on metadata-ingestion/tests/integration/iceberg/test_iceberg.py
> +        deleted_mces_path = "{}/{}".format(tmp_path, "iceberg_deleted_mces.json")
I think we could also have done `tmp_path / "iceberg_deleted_mces.json"`

2022-11-02 12:54 UTC, cccs-eric approved these changes

2022-11-02 12:59 UTC, merged